:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: apartments
:repository: Apartments
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:imagesdir: img/
:toc:
:toc-placement!:

= Apartments

image:https://github.com/av1m/Apartments/workflows/Java%20CI%20with%20Maven/badge.svg["Build Status", link="https://github.com/av1m/apartments/actions?query=workflow%3A%22Java+CI+with+Maven%22"]
image:https://www.codefactor.io/repository/github/av1m/apartments/badge["Codefactor", link="https://www.codefactor.io/repository/github/av1m/apartments/"]
image:https://img.shields.io/badge/License-MIT-color["License MIT]

A Java project developed by students during the link:https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in link:http://www.mido.dauphine.fr/[MIDO] L3 Apprentissage).

The code is hereby published under the link:LICENSE[MIT License], with their permission.

toc::[]

== Java iteration 🏃

=== Iteration 1

For our first run on the project, we have chosen to work on two main tasks:

* Adapt the program ton run with JSON stored apartments. 

* Clean the project from its unneeded dependencies and create an Apartment factory that will build immutable Apartment Objects  

From there and since we divided our group of 5 people into 2 groups, we decided to allocate one point per group (2x 2 teams for development + one for SM/PO, see `members` subparts for details)

==== Team 1

===== Members

- link:https://github.com/MorganeFt[Morgane FIOT]
- link:https://github.com/EtienneCartier[Etienne CARTIER]

===== Realizations

The first group will oversee the JSON adaptation of the apartment storage. We are planning to use the JSON writer link:https://javaee.github.io/jsonb-spec/getting-started.html["JSON Builder"] and add the corresponding dependencies. The function will take the number of Apartment desired and the location of the JSON file it will have to write in as parameters. We will have to modify the functions that run with the XML format (the write function in the FromApartmentGUI class). +
We will begin to change the storage place of the apartments created in the first place. When this will be ok and functional, we will dive into it to truly randomise the creation of the apartments if this is possible to randomise the generation of addresses if it adds something to the project.  

Finally, we will add a JSONConvert static class with three functions:

* *apartmentToJson* get an `Apartment` and an *optional string* as attributes of the function and it does not return anything. +
The Apartement is the data to store in the JSON file, and the String is the path of JSON file to write in. The function will make an error if it could not write the Apartment in the file properly. 

* *apartmentsToJson* get an *array of Apartment* and an *optional string* as attributes of the function and it does not return anything. +
The array of Apartement is the data to store in the JSON file, and the String is the path of JSON file to write in. The function will make an error if it could not write the Apartment in the file properly. 

* *jsonToApartments* take an *optional string* as attribute and return an array of Apartment. The string is the path of the JSON file to read in and the array of Apartment is the data parsed from the JSON file. 

* If there is no character string, it will look in `filePath` (an enum public) for the default path of the files with which the program interacts

`FilePath` : This enumeration will store all the adresses of the different files used by the program. We have nowdesigned it to be an enumeration with associated values (like a map struct in other languages), but we could also use an abstract class and a HashMap that get the values from a config file. This would allow the user to personalise the default file name in the config file. 

==== Team 2

===== Members

- link:https://github.com/clemencecousin[Clémence COUSIN]
- link:https://github.com/GabG02[Gabriel GUISSET]

===== Realizations

The second group will have to delete the Joda Time dependency and remove all other unnecessary dependencies. +
Following our primary researches, it appears that this dependency is never used in the program. We will run tests to make sure of that.

The group will also have to build the Apartment factory. We will replace the function ApartmentGenerator class with an ApartmentFactory class to build the immutable apartments. In Apartment Factory, we have different ways to generate one or more Apartments, we can use: 

* **GenerateApartment**: Takes all the data of an Apartment as parameters and returns the Apartment Object with the corresponding data. 

* **GenerateRandomApartment**: Does not take any parameter and it returns a randomly generated Apartment Objet. 

* **GenerateRandomApartmentList**: Takes the number of Apartments to generate randomly as parameter and return an array of Apartments of this size. 

* **GenerateApartmentFromJson**: takes an optional string as a parameter and will call the function JSONToApartment from the class JSONConvert to return the list of the apartments present in the Json file. 

==== Team 3 (SM/PO)

===== Members

- link:https://github.com/av1m[Avi MIMOUN]

===== Realizations

- Check the general adequacy of the project
- Facilitates and helps developers (Check for Github Apps and Github Actions)
- Indicates development priorities
- Help to test the project
- Manage Github (Addition of collaborator, Add Collaborators, Restricting rights, Creation of necessary branches, Creation of milestones, Update Travis, ...)

=== Iteration 2

[NOTE]
====
Both teams will do their utmost to minimize the number of warnings (already present) in the packages they will touch.
====

==== Team 1

===== Members

- link:https://github.com/MorganeFt[Morgane FIOT]
- link:https://github.com/av1m[Avi MIMOUN]

===== Realizations

Random generation of an apartment :

* Generate a large number of apartments in order to store the result in resources
* Generate latitude and longitude points in the Paris area to retrieve an address using the link:https://api-adresse.data.gouv.fr/reverse/?lon=2.2712946&lat=48.869962[government API]
* Use link:https://github.com/oliviercailloux/sample-rest-client[jax-rs client] link:https://github.com/av1m/Apartments/pull/3#discussion_r410394483[instead of InputStream] to make the HTTP GET request (link:https://github.com/av1m/Apartments/issues/5[issue #5])
* Modify the function which converts the HTTP return from the API (concerning addresses) to a string (`getAddressFromJson`)
* Modify the behavior of the `retry` during the API call, see link:https://github.com/av1m/Apartments/issues/7[issue #7]
* [OPT] Implement a function/pattern to determine if an address is correct

==== Team 2

===== Members

- link:https://github.com/clemencecousin[Clémence COUSIN]
- link:https://github.com/EtienneCartier[Etienne CARTIER]

===== Realizations

* Delete the `apartmentGenerator` class. Replace in `apartementFactory` (see link:https://github.com/av1m/Apartments/pull/3[PR #3])
* Specify unit tests, mainly for the `valueFunction`. Correction of documentation
* Warnings optimizations (package by package)

==== Team 3 (SM/PO)

===== Members

- link:https://github.com/GabG02[Gabriel GUISSET]

=== Iteration 3

==== Team 1

===== Members

- link:https://github.com/GabG02[Gabriel GUISSET]
- link:https://github.com/EtienneCartier[Etienne CARTIER]

===== Realizations

* Creation of everything related to the Profile:
    - Creation of `ProfileType` enumeration which contains our 3 types of Profile: `student`, `family` and `couple`.
    - Creation of the `Profile` class. This class contains the min, max and weight value for every parameters of the value function according to the parameters selected by the user. The Profile is also convert into an AVF.
    - Creation of the `ProfileManager` class which initialize all `Profile`.
* Fixing issue link:https://github.com/av1m/Apartments/issues/23[#23]

==== Team 2

===== Members

- link:https://github.com/clemencecousin[Clémence COUSIN]
- link:https://github.com/av1m[Avi MIMOUN]

===== Realizations

* Creation of everything related to the Question:
** Creation of `QuestionType` enumeration which contains our 4 questions to better adapt the ValueFunction.
** Creation of the `Question` class which gather the question from `QuestionType`
** Creation of 3 distinct classes for the 3 types of question we ask the user:
    *** `QuestionDoubleDouble` class
    *** `QuestionBestCriteria` class
    *** `QuestionDoubleBoolean` class

+
This 3 classes will contain the different possibility of answers and a resolve function which will adapt the AVF according to the user answer.
* Implementation of the link:https://github.com/google/google-java-format[google java format]
* Fixing link:https://github.com/av1m/Apartments/issues/20[issue #20] by the creation of an adapter
* For `ReadTwoApartmentsTest`:
    ** Remove the main method
    ** Removal of the `InputStream`
    ** Implement JSON
    ** Implement Unit Test
* Deletion of Redundancy on ApartmentValueFunction

==== Team 3 (SM/PO)

===== Members

- link:https://github.com/MorganeFt[Morgane FIOT]

===== Realizations

* link:Doc/changelog.adoc[Changelog]

== Get started ✨

Make sure you have installed link:https://openjdk.java.net/projects/jdk/11/[java 11], link:https://git-scm.com/[git] and  link:https://maven.apache.org/[maven]

[TIP]
====
Useful links:

* link:https://github.com/oliviercailloux/java-course/blob/master/Best%20practices/Various.adoc#installing-the-jdk[JDK]
* link:https://github.com/oliviercailloux/java-course/blob/master/Maven/README.adoc[Maven]
====

1. Clone the application
+
[source,bash]
----
git clone https://github.com/oliviercailloux/Apartments.git
----

2. Run unit tests
+
[source,bash]
----
cd Apartments/
mvn test 
----

== Documentation 📙

- Project documentation and UML iterations can be found in the directory link:Doc/README.adoc[*Doc/*]

== Code style 📄

In order to meet the greatest needs and not to restrict development to a common IDE, we have integrated link:https://github.com/google/google-java-format/blob/master/README.md[google-java-format]

In this sense, link:https://github.com/google/google-java-format/blob/master/README.md[google-java-format] is a program that reformats Java source code to comply with link:https://google.github.io/styleguide/javaguide.html[Google Java Style Guide].

The advantage of using this program is that it can be integrated as:

* link:https://github.com/google/google-java-format/blob/master/README.md#from-the-command-line[CLI command]
* IDE plugin (link:https://github.com/google/google-java-format/#intellij-android-studio-and-other-jetbrains-ides[Jetrains IDEs], link:https://github.com/google/google-java-format/#eclipse[Eclipse], etc.)
* link:https://github.com/google/google-java-format/blob/master/README.md#third-party-integrations[Third Party]
* link:https://github.com/google/google-java-format/blob/master/README.md#third-party-integrations[Github Actions]
* link:https://github.com/google/google-java-format/blob/master/README.md#as-a-library[Library (dependencies)]

In this project, we have integrated:

* CLI, I recommand this command : `java -jar /putYourPath/toFile.jar --replace $(git ls-files *.java)`. +
It works on Windows (PowerShell), Linux and MacOS
* a link:.github/workflows/maven.yml[Github Actions] : allows to format the code at each push (if ever a person has forgotten) or for all other types of events
* a maven plugin (in the link:pom.xml[pom] file): link:https://github.com/coveo/fmt-maven-plugin[coveo/fmt-maven-plugin] : allows you to format the code for each build with `mvn` of the application (locally). For example, by performing a `mvn test`, you will have the return of your tests as well as your formatted code. see on link:https://search.maven.org/artifact/com.coveo/fmt-maven-plugin[maven central]
+
TIP: You can use `mvn fmt:format`, `mvn compile`, `mvn build`, `mvn test` or any command who calls `build` (`mvn fmt:check` allows to check if files are to be formatted)

We also assume that formatting is done with the optimization of imports

I personally don't recommend the use of plugins for IDE because it requires user configuration, those which can cause problems (import optimizations and others). However, the use of plugins for IDE remains completely personal to each developer 👨‍💻.

Moreover, you can also use link:https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks[Git Hooks] by configuring the use of pre-commit so that your code is directly formatted with each commit.

.Be careful of :
[CAUTION]
====
* Executing a `main` method or unit tests from an IDE does not involve calling maven. On some IDEs, it's possible to specify that you want to use maven (instead of the internal IDE system), but this is not the case by default.
* Control that the version on Github actions, on fmt-maven-plugin and on the other integrations still the same!
====

== Changelog 🆕

- Link of link:Doc/changelog.adoc[changelog]

== Repository available on Github :octocat:

- Link of this link:https://github.com/av1m/Apartments[repository]

== Contributors 👨‍💻

- link:https://github.com/oliviercailloux[oliviercailloux]

=== 2020
.See contributors
[%collapsible]
====
- link:https://github.com/EtienneCartier[EtienneCartier]
- link:https://github.com/MorganeFt[MorganeFt]
- link:https://github.com/GabG02[GabG02]
- link:https://github.com/clemencecousin[clemencecousin]
- link:https://github.com/av1m[av1m]
====

=== 2019

.See contributors
[%collapsible]
====
- link:https://github.com/Amioplk[Amioplk]
- link:https://github.com/LaurenceTsizaza[LaurenceTsizaza]
- link:https://github.com/zeinaalwazzan[zeinaalwazzan]
- link:https://github.com/alexisperdereau[alexisperdereau]
- link:https://github.com/Aichaaa[Aichaaa]
- link:https://github.com/SandraSalame[SandraSalame]
- link:https://github.com/aitalibraham[aitalibraham]
====

=== 2018

.See contributors
[%collapsible]
====
- link:https://github.com/marccohen92[marccohen92]
- link:https://github.com/SlowVirtuousGiant[SlowVirtuousGiant]
- link:https://github.com/Deeplygends[Deeplygends]
- link:https://github.com/DAYAUX[DAYAUX]
====

== License 📝

* link:LICENSE[MIT]

[%hardbreaks]
link:#toc[⬆ back to top]
