= Apartments
-----------------------------

Build status : image:https://travis-ci.org/Deeplygends/Apartments.svg?branch=master["Build Status", link="https://travis-ci.org/Deeplygends/Apartments"]

A Java project developed by students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] L3 Apprentissage).

The code is hereby published under the MIT License, with their permission.

=== Livraison 1 ===

Pour cette première itération, notre but était de partir d’un projet propre, lisible et compréhensible par tous. Maintenant que cela est fait, nous allons commencer la deuxième itération. (Aucun besoin de faire des tests unitaires en plus par exemple)

=== Livraison 2 ===

Après avoir pris connaissance des remarques sur le départ du projet et avoir compris les enjeux des focntionnalités proposées, voilà comment nous avons décidé de travailler pendant cette itération :

* XMCDA Remis à plus tard

....
Avec le nouvel exemple disponible et un peu plus de recul, 
nous étudions la possibilité de reprendre ce sujet à partir de la 3e itération
....

* GUI qui montre à l’utilisateur tous les appartements disponibles dans un répertoire donné en paramètre, triés selon l’utilité de l’utilisateur (fournie dans un fichier dans le même répertoire). L’utilisateur peut cliquer sur un appartement et voit sa description

* Rendre plus général les fonctions d'utilité des utilisateurs : linéaires par morceaux

* Générer aléatoirement des annonces d'appartements

....
Cela permettra de tester les fonctionnalités liées à l'utilité de manière plus impartiale.
....

=== Livraisons 3&4 ===

* Extraction d’annonces depuis pap.
** Trouver les informations sur le code HTML
** Créer un fichier XML à partir de ces informations

* L’utilisateur indique son utilité de localisation par rapport à plusieurs lieux.

* L’utilisateur se fait aider pour déterminer son utilité. Il voit le résultat de sa spécification d’utilité sur des annonces concrètes du système.

* L’utilisateur peut indiquer en voyant la liste d’annonces qu’il préfère une annonce à une autre alors qu’elle est classé sous la deuxième. Le système lui permet alors de corriger son utilité pour que le classement en question soit rétabli.
