:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:imagesdir: img/
:toc:
:toc-placement!:

= Packages 📦

This file explains how the different application packages work

The actual program is divided in few packages:

toc::[]

== apartment

This is the most important package in the application

This part explains the model of an apartment and creation methods of apartments.

The creation of an apartment is done using a builder.

The `ApartmentFactory` class allows you to manage the creation of an apartment

=== Address generation for random apartment

This section deals with the generation of random apartments.

The challenge is then to generate addresses randomly as a function of latitude and longitude.

[NOTE]
====
Longitude and latitude are restricted in a geographic area.
====

You can see an implementation in `ApartmentFactory#getOnlineRandomAddress()` 

Indeed, the logic is to generate a longitude/latitude as explained above. Then reverse the longitude and latitude using the link:https://geo.api.gouv.fr/adresse[government API] by calling a JSON parser

== distance

Yhe only class we can find in this package is used to calculate distance between 2 points of a map. +
We can use it with 2 modes:

- *Address Mode*: To build distance between 2 addresses given to the constructor. 
- *Coordinate Mode*:  To build distance from coordinate (type of the Google Maps dependency:  LatLng) 

== gui

All this package concerns the Graphical User Interface and all interactions with the user. +
It’s very important for this package to do minimum operations linked to the thoughts of the program and keep only his role of builder of the display for the user and to send all requests to the thought part of the code.

== iconDisplay

This package contains a class getting the logo of the application. +
This class is used by some of GUI package classes. +
We can imagine moving this class in the `utils` package. 

== localize 

Inside, we can find a class which allows the program to get *the location of* an address using GoogleMaps’ API. +
This class is used only in test part.

== readapartments 

The class which compose this package is `ReadApartmentsXMLFormat` and allows us to get an apartment form an XML file. We can imagine making this class an abstract and the operations static because we don’t have to keep in memory immediately treated data. +
Another improvement idea can be to move this class in the `utils` package. 

== toxmlproperties 

This package has a class called `XMLProperties` which allows us to export apartment’s informations in a XML file. +
We can also imagine moving it in the `utils` package. 

== utils

This package combines all functionality which can help all classes of the program. +
All classes, global logic method and helper class, are organized in this packages package. In fact, if we want to change well-known method (like a date comparator) to adapt it to our needs, we can do it here.

== valuefunction

This package includes thoughts about calculating the satisfaction of a property's criteria for a customer

The valueFunction package gathers all the functions which attribute a value to each apartment according to some criteria. +
The functions of this package are called by AskOpinionForUtilities class. Apartments are sorted by value to show the user the apartments which are the most likely to suit them.

* *`PartialValueFunction<T>` interface*
+
This interface attributes a subjective value to a parameter. This is interface extends the class Function<T, Double> which transform the generic type in input to a double: see link:https://docs.oracle.com/javase/8/docs/api/java/util/function/Function.html[here]
+
This interface uses a getSubjectiveValue(T objectiveData) method and can throws an IllegalArgumentException. objectiveData is the parameter on which we want to get the subjective value between 0 and 1.

* *`ApartmentValueFunction` class*
+
This class create an object `ApartmentValueFunction` from the different classes in the package. Every criterion, such as the number of bedrooms, the presence of a terrace or the TV, etc., is associated to a value and a weight. +
The default value for the criterion is 0 and its default weight is 0.1. At the end, the ApartmentValueFunction method returns the value of the apartment, that is the weighted sum of all criterion value divided by the sum of all weight. It’s a basic weighted average. 

* *`LinearValueFunction` class & `ReversedLinearValueFunction` class* 
+
The tricky part is that you can’t ask the user to attribute a value between 0 and 1. +
As we saw, `AskOpinionForUtilities` only ask the user how many bedrooms he desires or the surface he would like to have. The `LinearValueFunction` class transforms a number (for example 5 bedrooms) into a value between 0 and 1 using linear interpolation
+
`ReversedLinearValueFunction` is only used for the minimal number of nights. `LinearValueFunction` is for the floor area and the price per night. 

* *`BooleanValueFunction` class*
+
`AskOpinionForUtilities` asks the user if he wants the WiFi, a TV or a terrace. According to the user responses, `BooleanValueFunction` attributes the value 1 if the user wants this 0 else.

We could find a way to simplify the attribution of a value to an apartment because every time we use `AskOpinionForUtilities`, the value of each apartment is once again calculated. +
Maybe we could also lighten the `ApartmentValueFunction` which is very long and redundant. +
Improving our way to calculate the “value” of an apartment according to criteria could be improved to propose the user better apartments.

[%hardbreaks]
link:#toc[⬆ back to top]
