:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:imagesdir: img/
:toc:
:toc-placement!:

= Documentation 📙

toc::[]

== Overview 👀

We decided to give a goal to our app and to define clearly the users of it. +
Indeed, the current state of the application is not obvious: it is difficult to see who will use the app and the uses of it. +
In other words, the current application has no real user. These are just features developed with no real link yet.

So, we decided to clarify these points. +
First, let’s talk about the goal of the app. We will try to develop this app so that it will be used for long-term apartment’s rental. +
Users will be able to see the different apartments and to select them according to the most important criteria for them. That led us to the second point: for whom will be this app designed. +
We decided that the main users of this app will be the tenants. The apartment’s owner won’t interact with the app. +
To put the apartments online and eventually to modify them, we add a second actor in our model : a manager. The role of this actor is basically to put the apartments online, to modify them if needed and to delete them if a place is rented for example.

== Runnable class 🏃

To have an overview of all executable classes, you can go to link:run.adoc[run.adoc]

== Packages 📦

A package-by-package explanation is available, in link:packages.adoc[packages.adoc]. +
*Most of the documentation is available in this file!*

== Diagrams UML

For an overview of all diagrams, you can see the link:img/[img/] folder or go directly to Papyrus.

In addition, link:global.adoc[global.adoc] includes all the global diagrams of the application &rarr; allows an overview.

[IMPORTANT]
====
We have detected that some themes prevent the proper functioning of papyrus (for example, transparent arrows). +
We noticed this bug with the link:https://www.genuitec.com/products/devstyle/[DevStyle theme] +
_Thanks link:https://github.com/GabG02[gab202]_
====

== Convention for naming packages (for papyrus)

* The name of a package must start with the type of diagram he contains (CD, UCD, ID) and should look like this: "TypeOfDiagram_Description”. +
The only exception is for the `JavaIteration` package as it may contain different type of diagram.
* When you create a new child such as a use case or a new class, the name of it should finish with "UC” if it is a use case, "CD” if it is for a class diagram or "I” for an interaction diagram.

== Idea 💡

For all ideas under development, not integrated into the application and the elements to be considered, please refer to link:idea.adoc[this documentation].

== Create API KEY

* It allows you to use the Google MAPS API to calculate the distance between two places. For example, in DistanceSubway Class, you need it.

* Go to https://console.cloud.google.com/ and connect to your google account (You must have one).

* On the top left, create a new project. Once it is created, click on it.

* Go to Api and Services, and then Credentials. Click on "Create credentials, API Key".

* You now have created a Key. Go to API Library and enable "Distance Matrix API, Geocoding API, Directions API, Maps Elevation API, Maps JavaScript API, Roads API".

* Go back to credentials, click on the key, and restrain it to only those API.

* Before using it, you must activate "Billing".

* To try it, go to DistanceSubway.java, create a string contaning the API KEY. Instanciate a DistanceSubway object with two adresses (or coordinates) and the key. 

* Using calculateDistanceAdress method, get the distance in seconds between those two adresses. Without the key, you wouldn't be able to use this class.

* Go back to the cloud google website, and verify that the API request was successful. (Be aware, you only have 300$ of free credits).


[%hardbreaks]
link:#toc[⬆ back to top]
